# Service for api gateway
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    type: service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
  selector:
    name: api-gateway
---
# Service for Utility microservice
apiVersion: v1
kind: Service
metadata:
  name: utility-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: utility
---
# Service for utility-monodb
apiVersion: v1
kind: Service
metadata:
  name: mongo-utility-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    name: mongo-utility
---
# Service for personal microservice
apiVersion: v1
kind: Service
metadata:
  name: personal-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: personal
---
# Service for personal-monodb
apiVersion: v1
kind: Service
metadata:
  name: mongo-personal-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    name: mongo-personal
---
# Service for investment microservice
apiVersion: v1
kind: Service
metadata:
  name: investment-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    name: investment
---
# Service for utility-monodb
apiVersion: v1
kind: Service
metadata:
  name: mongo-investment-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    name: mongo-investment