apiVersion: networking.k8s.io/v1beta1
kind: ingress
metadata:
  name: public-routing
spec:
  rules: 
    - host: khandelwal.com
      http: 
        paths: 
          - path: /utility
            backend: 
              serviceName: utility-service
              servicePort: 8080