# Service for Utility microservice
apiVersion: v1
kind: Service
metadata:
  name: utility-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      # targetPort: 8080
  selector:
    name: utility
---
# Service for utility-monodb
apiVersion: v1
kind: Service
metadata:
  name: mongo-utility-service
  labels:
    type: service
spec:
  type: ClusterIP
  ports:
    - port: 27017
  selector:
    name: mongo-utility