# What do we want from storage perspective
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
---
# How do we want it to get implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloud-ssd    #Should match with StorageClassName of PersistentVolumeClaim
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2